snd-soc-ac108-objs := ac108.o 
#snd-soc-seeed-voicecard-objs := seeed-voicecard.o

obj-$(CONFIG_SND_SOC_AC108)   += snd-soc-ac108.o
#obj-$(CONFIG_SND_SOC_SEEED_VOICECARD)   += snd-soc-seeed-voicecard.o
